spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url:  "jdbc:mysql://mydb.cd2ixijusx48.ap-northeast-2.rds.amazonaws.com:3306/blogs"
    username: "admin"
    password: "!dmssk6480"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect