server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url:  "jdbc:mysql://mydb.cd2ixijusx48.ap-northeast-2.rds.amazonaws.com:3306/blogs"
    username: "admin"
    password: "!dmssk6480"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
config:
  jwt-key: "MAmlSvtB7CXj9aBa/5nl/eAk+N34PejDmR7QMP59mnw="
