spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: "jdbc:mysql://localhost/blogs"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
