### 로그인

POST http://localhost:9000/auth/login
Content-Type: application/x-www-form-urlencoded


username=qwer@co.kr&password=1234

### 회원가입

POST http://localhost:9000/auth/signup
Content-Type: application/json

{
  "name": "qwer",
  "email" : "qwer@co.kr",
  "password": "1234"
}

### 메인페이지

GET http://localhost:9000